# Generated by Django 4.0.4 on 2022-11-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frase',
            name='significado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
