# Generated by Django 4.0.4 on 2022-11-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frase',
            name='frase',
            field=models.CharField(max_length=250),
        ),
    ]
