# Generated by Django 4.0.4 on 2022-11-13 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiAuth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nombres',
            new_name='nombre',
        ),
    ]
