# Generated by Django 4.0.4 on 2022-11-12 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiAuth', '0002_codigoauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizacion',
            name='codigo_auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiAuth.codigoauth'),
        ),
        migrations.AlterField(
            model_name='codigoauth',
            name='codigo_auth',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
