# Generated by Django 4.0.4 on 2022-11-13 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiAuth', '0003_unidad_alter_usuario_unidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigoauth',
            options={'verbose_name': 'CodigoAuth', 'verbose_name_plural': 'CodigosAuth'},
        ),
        migrations.AlterModelOptions(
            name='unidad',
            options={'verbose_name': 'Unidad', 'verbose_name_plural': 'Unidades'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
