# Generated by Django 4.0.4 on 2022-11-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiAuth', '0004_alter_autorizacion_codigo_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoauth',
            name='codigo_auth',
            field=models.CharField(max_length=20),
        ),
    ]
