# Generated by Django 4.0.4 on 2022-11-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiAuth', '0005_alter_codigoauth_codigo_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoauth',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
