# Generated by Django 4.0.4 on 2022-11-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiAuth', '0007_alter_autorizacion_codigo_auth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigoauth',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='codigo_auth',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='codigoauth',
            name='codigo_auth',
            field=models.CharField(max_length=25),
        ),
    ]
