# Generated by Django 4.0.4 on 2022-11-12 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiAuth', '0008_remove_codigoauth_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autorizacion',
            name='codigo_auth',
        ),
        migrations.AddField(
            model_name='codigoauth',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiAuth.autorizacion'),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='usuario',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='codigoauth',
            name='codigo_auth',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
