# Generated by Django 4.0.4 on 2022-11-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiAuth', '0009_remove_autorizacion_codigo_auth_codigoauth_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autorizacion',
            name='apellido',
        ),
        migrations.AddField(
            model_name='autorizacion',
            name='apellidos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='codigoauth',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='usuario',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
