# Generated by Django 4.0.4 on 2022-11-13 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiAuth', '0010_remove_autorizacion_apellido_autorizacion_apellidos_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autorizacion',
            new_name='Usuario',
        ),
    ]
